[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_foundry"

[rpc_endpoints]
blockdag = "https://rpc.primordial.bdagscan.com"



[chain_ids]
blockdag = 1043
