[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache_foundry"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
blockdag = "https://rpc.primordial.bdagscan.com"

[profile.default.chain_ids]
blockdag = 1043